In [1]:
import numpy as np

#Create a random array that is 5 x 5
X = np.random.rand(5, 5)

#Set the values
mean = np.mean(X)
std = np.std(X)
Z = (X - mean) / std

#saving
Normalized_X = np.save("X_normalized.npy", Z)

#printing the output
print("Your current value: " + str(X))
print("Your normalized value: " + str(Z))

Your current value: [[0.79734895 0.2894842  0.25893706 0.14694201 0.1094104 ]
 [0.07596643 0.60125185 0.32691227 0.21889702 0.34183722]
 [0.62428312 0.14069875 0.93262653 0.04607238 0.45364054]
 [0.35307969 0.54233981 0.70073701 0.6109565  0.17355964]
 [0.35265143 0.54407486 0.23362842 0.24678614 0.72716084]]
Your normalized value: [[ 1.67850514 -0.43478408 -0.56189458 -1.0279201  -1.18409384]
 [-1.32325843  0.86252038 -0.27904115 -0.72850623 -0.21693655]
 [ 0.95835643 -1.05389909  2.24141218 -1.44765131  0.24829113]
 [-0.17015523  0.61737997  1.27649068  0.90290265 -0.9171608 ]
 [-0.1719373   0.62459972 -0.66720701 -0.61245611  1.38644355]]
